### ISSUE TITLE
network error

### ISSUE THREAD

**Issue by seteahconnoc** [suri909/Kst_Workadventure#1]
Auf dem Github-Fileserver kann ich das Projekt nach wie vor nicht nutzen (network error, map.json).

**Comment by suri909** [comment]
Ich habe keine Ahnung, wie das seien kann. : (

**Comment by seteahconnoc** [comment]
Mit dem Issue [https://github.com/suri909/Kst_Workadventure/issues/2](url) wurde auch dieses Problem gelöst.
