### ISSUE TITLE
Lokaler Bilder-Ordner

### ISSUE THREAD

**Issue by seteahconnoc** [suri909/Kst_Workadventure#2]
Lokal läuft bei mir vieles wunschgemäß. Nur habe ich keinen Zugriff auf Bilddateien, die offensichtlich lokal bei dir auf dem Desktop abgelegt worden sind.

**Comment by suri909** [comment]
Eigentlich ist in dem Ordner "tileset" eine png-Datei. Genauso wie die anderen Dateien. Das ist nur diese PNG Datei!

**Comment by seteahconnoc** [comment]
Entfernung des Kachelsatzes "MAP". Dieser verwies auf einzelne PNG-Dateien auf dem lokalen Speicherort "Desktop".
