### ISSUE TITLE
Zu kleine Map

### ISSUE THREAD

**Issue by seteahconnoc** [suri909/Kst_Workadventure#3]
Die augenblickliche Map ist zu klein. Es kann nicht das gesamte Schulgelände dargestellt werden.

**Comment by suri909** [comment]
Bin auch noch nicht fertig

**Comment by suri909** [comment]
Ich erweitere sie immer weiter.

**Comment by seteahconnoc** [comment]
Ich hatte es so verstanden, dass du die Möglichkeit zur Vergrößerung der Map noch nicht gefunden hattest und somit "auf dem Grundstück" keinen Platz für neue Gebäudeteile hattest. Diese Möglichkeit gibt es im "tiled"-Editor unter dem Menüpunkt: Karte -> Kartengröße ändern...

![Bildschirmfoto von 2022-12-29 17-40-52](https://user-images.githubusercontent.com/23081344/209983429-06fdeaf2-3bc6-42cc-b4af-073a6334e407.png)

Siehe auch [HIER](https://discourse.mapeditor.org/t/change-map-size/4132).

Ich werde das jetzt NICHT ändern, um zu vermeiden, dass wir uns beim Editieren in die Quere kommen. Ich gehe davon aus, dass dir die Sache nun auch klar ist.

Markiere diesen "issue" gern als "erledigt" oder stelle eine Nachfrage.
