### ISSUE TITLE
Stockwerke

### ISSUE THREAD

**Issue by seteahconnoc** [suri909/Kst_Workadventure#4]
Sollen Stockwerke implementiert werden?

Pro: größere Realitätsnähe (insb. hinsichtlich der Fachräume für Biologie und Chemie).
Contra: Das Projekt wird unnötig komplex.

**Comment by seteahconnoc** [comment]
Ich hatte es bereits angedeutet: Stockwerke lassen sich (z. B.) mit "Entries & exits" realisieren. Siehe [HIER](https://workadventu.re/map-building/entry-exit.md).

**Comment by suri909** [comment]
Ich würde die oberen Stockwerke nicht alle nachbauen. Ich würde nur implementieren, dass wenn man die Treppe berührt, man in den 3. Stock kommt (Entries & Exits). Bei Physik würde ich einen Teil des Gebäudes bauen, damit Erdkunde auch dabei ist.

**Comment by suri909** [comment]
Und ein Teil des 2. Stockes für Informatik wird auch gebaut.

**Comment by suri909** [comment]
Mache jetzt erst das ganze 1. Stockwerk fertig. Dann läuft das alles schneller, da ich Deko etc. dann habe.

**Comment by seteahconnoc** [comment]
Meine erste Idee wäre, grundsätzlich keine Stockwerke zu implementieren. Man müsste sich für den jeweils interessantesten Raum an den entsprechenden xy-Koordinaten entscheiden - Beispiele:
- Am Südende des Südtrakts wird nur der Informatik-Raum gesetzt.
- Am Nordende des Stüdtrakts wird nur ein Biologie-Raum gesetzt.
- In den Osttrakt wird die Physik gesetzt.
- ... usw.

Es sollte recht selten sein, dass zwei für dieses Projekt interessante Räume direkt übereinander liegen.

**Comment by seteahconnoc** [comment]
Ein weiterer Punkt: Hinsichtlich der Kollaboration am Tag der offenen Tür hat es gewisse Vorzüge, wenn das digitale Gebäude nicht zu groß ist. Auf diese Weise trifft man häufiger auf andere Avatare.

**Comment by seteahconnoc** [comment]
Aber entscheide gern selbst. Ich gebe nur Ideen.
